spring:
  banner:
      location: classpath:/banner/banner.txt
      
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: true # Whether to enable template caching.
    check-template: true # Whether to check that the template exists before rendering it.
    check-template-location: true # Whether to check that the templates location exists.
    enabled: true # Whether to enable Thymeleaf view resolution for Web frameworks.
    enable-spring-el-compiler: false # Enable the SpringEL compiler in SpringEL expressions.
    encoding: UTF-8 # Template files encoding.
    excluded-view-names: # Comma-separated list of view names (patterns allowed) that should be excluded from resolution.
    mode: HTML # Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    reactive:
      chunked-mode-view-names: # Comma-separated list of view names (patterns allowed) that should be the only ones executed in CHUNKED mode when a max chunk size is set.
      full-mode-view-names: # Comma-separated list of view names (patterns allowed) that should be executed in FULL mode even if a max chunk size is set.
      max-chunk-size: 0B # Maximum size of data buffers used for writing to the response.
      media-types: # Media types supported by the view technology.
    render-hidden-markers-before-checkboxes: false # Whether hidden form inputs acting as markers for checkboxes should be rendered before the checkbox element itself.
    servlet:
      content-type: text/html # Content-Type value written to HTTP responses.
      produce-partial-output-while-processing: true # Whether Thymeleaf should start writing partial output as soon as possible or buffer until template processing is finished.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    template-resolver-order: # Order of the template resolver in the chain.
    view-names: # Comma-separated list of view names (patterns allowed) that can be resolved.